---
- name: Ensure configuration
  ansible.builtin.template:
    src: env.j2
    dest: "{{ vaultwarden_directory }}/.env"
    owner: vaultwarden
    group: vaultwarden
    mode: u=rw,go=
  notify: Restart vaultwarden

- name: Copy encryption rsa key
  ansible.builtin.copy:
    content: "{{ vaultwarden_encryption_key }}"
    dest: "{{ vaultwarden_datadir }}/rsa_key.pem"
    owner: vaultwarden
    group: vaultwarden
    mode: u=rw,go=
    force: "{{ vaultwarden_force_encryption_key }}"
  register: __vaultwarden_copy_encryption_rsa_key
  when: vaultwarden_encryption_key|length > 0

- name: Setup systemd service
  ansible.builtin.template:
    src: systemd.service.j2
    dest: /lib/systemd/system/vaultwarden.service
    mode: u=rw,go=r
  notify: Restart vaultwarden
  when: vaultwarden_systemd
