---
- name: Gather OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - vaultwarden_install
    - vaultwarden_configure
    - vaultwarden_run

- name: Include the vaultwarden version playbook
  ansible.builtin.include_tasks: version.yml
  tags:
    - vaultwarden_install

- name: Include the vaultwarden install playbook
  ansible.builtin.include_tasks: install.yml
  tags:
    - vaultwarden_install

- name: Include the vaultwarden configure playbook
  ansible.builtin.include_tasks: configure.yml
  tags:
    - vaultwarden_configure

- name: Ensure vaultwarden started and enabled
  become: true
  ansible.builtin.systemd:
    name: vaultwarden
    state: started
    enabled: true
    daemon_reload: true
  when: vaultwarden_systemd
  tags:
    - vaultwarden_run
